### ISSUE TITLE
Extra `tyro.conf.OmitSubcommandPrefixes`

### ISSUE THREAD

**Issue by brentyi** [openrlbenchmark/openrlbenchmark#15]
Hi @vwxyzjn!

The usage of `tyro.conf.OmitSubcommandPrefixes` here:
https://github.com/openrlbenchmark/openrlbenchmark/blob/751708bd1f81f90c59476ac832dae91c0550eea3/openrlbenchmark/rlops_hns.py#LL82C9-L82C41
is a no-op, since `openrlbenchmark` doesn't currently have any subcommands ([examples of subcommands](https://brentyi.github.io/tyro/examples/02_nesting/02_subcommands/)).

Was the intention to drop the `--pc.` prefix in generated arguments?

**Comment by brentyi** [comment]
Got it!

Currently this can be accomplished by removing the name of the `pc` field:
```python
pc: Annotated[PlotConfig, tyro.conf.arg(name="")] = field(default_factory=PlotConfig)
```
But possibly we can come up with something more user-friendly, like `tyro.conf.Flatten[]`?

**Comment by vwxyzjn** [comment]
Ah this is great. Would `tyro.conf.OmitArgPrefixes` be a more consistent name? Also kind of curious, what happens in the case of duplications? Like there is ` --pc.flag` and `--flag`.

**Comment by brentyi** [comment]
As of `0.5.0` if you have two args called `nrows: int`, `--nrows` will be used to instantiate both of them. The help message will only show info for the first one. Maybe this is confusing, and we should instead raise an error?

**Comment by vwxyzjn** [comment]
In the case of duplication, an error is probably better

**Comment by vwxyzjn** [comment]
Thanks a lot @brentyi! After thinking a bit I am thinking of keeping the current `--pc.flag` behavior since I already made the breaking change. In the future, however, I think `tyro.conf.OmitArgPrefixes` will be super helpful :)

**Comment by brentyi** [comment]
Ok, sounds good!
